// Catálogo local de Marcas y Modelos de Vehículos populares
export const POPULAR_CARS = {
  Toyota: [
    "Corolla",
    "Yaris",
    "RAV4",
    "C-HR",
    "Auris",
    "Prius",
    "Land Cruiser",
    "Hilux",
  ],
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Altea", "Toledo"],
  Renault: [
    "Clio",
    "Megane",
    "Captur",
    "Kadjar",
    "Scenic",
    "Zoe",
    "Laguna",
    "Twingo",
  ],
  Volkswagen: [
    "Golf",
    "Polo",
    "T-Roc",
    "Tiguan",
    "Passat",
    "Touran",
    "ID.3",
    "ID.4",
    "Caddy",
  ],
  Peugeot: ["208", "308", "2008", "3008", "5008", "508", "Partner", "Rifter"],
  Ford: [
    "Fiesta",
    "Focus",
    "Kuga",
    "Puma",
    "Mondeo",
    "Mustang",
    "C-Max",
    "Transit",
  ],
  Opel: ["Corsa", "Astra", "Mokka", "Grandland", "Insignia", "Zafira"],
  Citroën: [
    "C3",
    "C4",
    "C3 Aircross",
    "C5 Aircross",
    "Berlingo",
    "Saxo",
    "Xsara",
  ],
  BMW: ["Serie 1", "Serie 3", "Serie 5", "X1", "X3", "X5", "i3", "Serie 4"],
  Audi: ["A1", "A3", "A4", "A6", "Q3", "Q5", "e-tron", "TT"],
  Mercedes: [
    "Clase A",
    "Clase C",
    "Clase E",
    "GLA",
    "GLC",
    "GLE",
    "EQA",
    "Vito",
  ],
  Hyundai: ["i20", "i30", "Tucson", "Kona", "IONIQ", "Santa Fe", "Getz"],
  Kia: ["Rio", "Ceed", "Sportage", "Stonic", "Niro", "Sorento", "Picanto"],
  Fiat: ["500", "Panda", "Punto", "Tipo", "Ducato", "500X"],
  Dacia: ["Sandero", "Duster", "Lodgy", "Logan", "Jogger"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X"],
  Nissan: ["Micra", "Qashqai", "Juke", "Leaf", "X-Trail"],
};

export const FUEL_TYPES = [
  { label: "Gasolina", value: "Gasolina" },
  { label: "Diésel", value: "Diesel" },
  { label: "Híbrido", value: "Hibrido" },
  { label: "Eléctrico", value: "Electrico" },
];

export const CAR_COLORS = [
  "Blanco",
  "Negro",
  "Gris Plata",
  "Gris Oscuro",
  "Azul",
  "Rojo",
  "Verde",
  "Amarillo",
  "Naranja",
  "Marrón",
  "Beige",
];
